version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:21.0.2
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout

      # Install Maven
      - run: mvn dependency:go-offline

      # Install Chrome and Chromedriver
      - run:
          name: Install latest version of Chrome
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable

      - run:
          name: Install correct version of ChromeDriver
          command: |
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
            wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip -d /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

      - run:
          name: Install Xvfb and other dependencies
          command: |
            sudo apt-get install libxi6 libgconf-2-4 -y
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install imagemagick x11-apps -y

      - run:
          name: Start Xvfb
          command: |
            Xvfb :0 -ac &
            export DISPLAY=:0
            
      # Cache dependencies to speed up build time
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Run Maven Tests
      - run:
          name: Run Maven Tests
          command: mvn clean test

      # Save Maven cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Archive Extent Reports
      - store_artifacts:
          path: Report/ExtenthtmlReport.html
          destination: ExtenthtmlReport.html

      # Archive Test Results (for CircleCI Test Insights)
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  test:
    jobs:
      - build
